### ISSUE TITLE
conflict with available Database we created

### ISSUE THREAD

**Issue by Ujjval-Patel** [sen-29/timetable#1]
this [line](https://github.com/sen-29/timetable/blob/017f0ef9e8283c21e3f67eb76668f293367032c7/Database/users.sql#L1) has a problem, According to the [database template](https://docs.google.com/document/d/1x9-m1M64q3-Lu12J69NH8QuZdG1PmzC3jRXhmUi_stc/edit) we created yesterday, instead of "user" this should be "person" and it is missing some attributes too.

**Comment by dhrumil29699** [comment]
It's temporary table we will change it.
